### ISSUE TITLE
Current method of onion routing has (positive?) effect on crypto implementation

### ISSUE THREAD

**Issue by DestructiveReasoning** [CamiloGarciaLaRotta/Cebolla#16]
Guys. This is pretty neat.
I was just working on #15, and while testing it I noticed we have been overlooking a really good property of the way we send onion packets now, which could entirely solve the problem of #4.
The way it stands right now, onion nodes create connections *only during the establishment process*. Once all connections for the circuit have been established, onions just keep sending data along the connections they already have. This means that once the circuit has been established, **the onion nodes don't need the address information for where to send the next packets**. Therefore, after the establishment  process that nested JSON stuff isn't necessary! Consequently, all the originator needs to send through the circuit is the message encrypted with everyone else's symmetric key. Ultimately, this means that intermediate nodes peel off layers of encryption, but don't actually remove any data from the cipher text (because no routing information is included anymore). So, the ciphertext size doesn't change throughout the onion network if we take advantage of this! This *might* require some modifications to `stealth/stealth.py` for the crypto to still work (and by that I mean keep a constant size when encrypting), but I think it is probably ready already.

Since what I'm suggesting here is pretty bold, I found it appropriate to include an issue here so we can discuss. Currently I'm testing #15 and I've concluded that once the circuit is established, the onion routers in fact do not care about anything aside from the final message data (and hence don't need the addresses we're sending to them). For example, I sent the following through the onion network after establishing a circuit through two onion nodes to the `dummy_dest.py`:
```Python
{
"addr": "google.ca",
"port": 34789,
"data": {
    "addr": "facebook.com",
    "port": 5551,
    "data": "hello, newman"
}
}
```
And I got a response of `"HELLO, NEWMAN"`, which is clearly a response from  #`dummy_dest.py`.
This means that if there's an issue with what I've described above, there is very likely an issue with how our onion routers are working, because they are now passing around useless data.

**Comment by DestructiveReasoning** [comment]
This actually also has an effect on how our network will be used. Right now each circuit is only valid for one destination, whereas originally I figured we'd have one circuit per originator. I was thinking we could include some property in the JSON to tell the onion node that it has to change its forward connection, but then we'd have layered JSON again which voids the constant ciphertext size property I mentioned before. 

I think a solution to this issue can be implemented in the originator client, but it may be challenging to implement so we should probably neglect it for now. For the sake of the project, it's probably alright just to open separate originator clients for each destination.

However, should we have the time, here's what I propose:
The originator client stores an dictionary of circuits (each running on their own thread). The keys for the dictionary can be the domain name of the destination that the circuit is connected to, for example if the originator contacts `http://www.google.ca/search?source=sdjlkjsdfklkjf...`, the connection will be stored with the key `www.google.ca` in the dictionary. Whenever the originator sends a new message, he checks if there's already a key in the dictionary with the new destination's domain name and sends it through that circuit if there is. Otherwise, the originator contacts the directory node again, establishes a new circuit (and inserts it with an appropriate key in the dictionary), and sends the message like usual.

**Comment by stumash** [comment]
## Concerning JSON formats that are unnecessary after `two_way_setup()`

write now in `onion.py` we have:

```python
def forward_transfer(back_conn, forw_conn):
    while True:
        msg = back_conn.recv(2048).decode('utf-8').rstrip()

        # (TODO: decrypt)

        # json parse
        msg_dict = json.loads(msg)
        msg_data = msg_dict["data"]
        msg_addr = msg_dict["addr"]

        # pass it on
        forw_conn.send(json.dumps(msg_data).encode('utf-8'))

def backward_transfer(forw_conn, back_conn):
    # (TODO: enrypt before) passing data from forw to back
    back_conn.send(  forw_conn.recv(2048).decode('utf-8').rstrip()).encode('utf-i')  )
```

You are 100% correct that we don't need to do the JSON parsing that we're doing in `forward_transfer`.  In `two_way_setup`, we parse a `addr` and `port` out of JSON message to create `forw_conn` and `back_conn` sockets.  Once we have these sockets, we can send messages over them without needing to re-parse `addr` and `port` from incoming messages (in fact those messages no longer need to include the info for `addr` and `port` at all).  I therefore support using a JSON format only for circuit establishment.  This does also solve the "standard length problem" #4 (except there will be some regularity in the size of the initial circuit-establishment/key-exchange message unless otherwise implemented).

### Concerning the originator client supporting more than one circuit at once

As you mentioned, I don't think we *need* this feature, though it would be cool if we could get to it.

I also agree that it would be challenging to implement (at the very least I'd like to have some discussions about how we'd have to change what we have now to get there).

So for those reasons, I agree that we should neglect it for now.  However, I like the dictionary  that stores `dest => circuit` mappings. This dictionary would go nicely with some imagined solutions to the fault tolerance issue I raised (#19).  Basically, when a node in a circuit goes down, we would just have all nodes in the circuit "leave the circuit" and the originator could put a new circuit in the `dest => circuit` dictionary, replacing the old one like nothing had happened.

**Comment by DestructiveReasoning** [comment]
Refactoring crypto in branch [refactorCrypto-22](https://github.com/CamiloGarciaLaRotta/Cebolla/tree/refactorCrypto-22).
