### ISSUE TITLE
fault tolerant end to end

### ISSUE THREAD

**Issue by stumash** [CamiloGarciaLaRotta/Cebolla#19]
Right now, if any of the onion routers in a virtual circuit go down or fail to communicate then all the threads involved just raise exceptions.   Onion nodes shall instead **shut down gracefully** when a virtual circuit is "opened" due to any failure of any of its nodes.  "Shut down gracefully" means two things:

1. The routers shall not raise uncaught exceptions and shall propagate news of the circuit's failure to all participating nodes before leaving the circuit themselves.  We would like the failure of any router in a virtual circuit to cause the circuit in question to "kill itself".
2.  The originator should be able to recover from the circuit's "death" by re-sending the failed transmission over a new circuit established in recovering from the failure of the first  one.

**Comment by DestructiveReasoning** [comment]
Yeah, this is definitely an issue that we should be fixing. It gets pretty ugly when connections don't work out so well.
There's one thing I'm not entirely clear on now and I don't have time to test at the moment: what happens if an onion node is connected on several circuits and one of its circuits experiences a failure? Does the onion node just 'die' and thereby render all of its other circuits useless? Perhaps the testing team can try that out.

**Comment by CamiloGarciaLaRotta** [comment]
+1 for making this a global issue,
I had thought of developing the error handling for the onion client, but it is much better to have a homogenized approach of shutting down any type of node

**Comment by CamiloGarciaLaRotta** [comment]
56577dc is a first step towards making gracefull shutdowns

**Comment by CamiloGarciaLaRotta** [comment]
4bc61fc is a second step in making graceful shutdowns. Now router nodes can be up while Directory goes up and down multiple times without a problem

**Comment by CamiloGarciaLaRotta** [comment]
Is the current level of fault tolerance enough?
@stumash

**Comment by DestructiveReasoning** [comment]
@CamiloGarciaLaRotta I'm not sure I understand the fault tolerance there, but from my experience testing the general onion network yesterday I'd say we still need to work on fault tolerance. For example, as I see it, once the client shuts down (by ^C for example), the node it was immediately connected to seems to die. Of course, this is a big problem because it ruins all other circuits that pass through that node.
